### ISSUE TITLE
The 'R' disappears from formula at max value

### ISSUE THREAD

**Issue by phetsims** [phetsims/resistance-in-a-wire#28]
In the current version, the "R" disappears completely from view at its max value.  In the Flash version, it is still visible behind everything else.  See screenshots for illustration.

![riaw-flash-version-max-R](https://f.cloud.github.com/assets/3045815/399793/f72601da-a87e-11e2-8999-3a26be24e096.png)

![riaw-html-version-max-R](https://f.cloud.github.com/assets/3045815/399794/ffa5007c-a87e-11e2-84ef-961839222806.png)

**Comment by bryo5363** [comment]
This bug is present on Microsoft Edge 25.10586.0.0

**Comment by bryo5363** [comment]
I noticed that this behavior does not need the resistance to be at the max value (at least for Microsoft Edge). I was experiencing this behavior with the following parameters 

Resistivity : 0.06
Length : 3.57
Area : 0.01

**Comment by zepumph** [comment]
This is happening in dev testing as part of https://github.com/phetsims/QA/issues/16, I am not really sure how to move forward, but @phet-steele and I are pretty sure that this was crashing his computer. For me (windows) it happens only on firefox (not chrome) and it won't crash anything, it just goes blank for a bit while it redraws or something like that. I think one solution could be to make the max size of R a bit smaller. Then the problem will be to balance how to do that while accurately portraying the formula to scale. 

What if the resistance got to a certain size and then started shaking or something like that, not sure I like that as a workaround.

**Comment by jonathanolson** [comment]
Could just grab path information from an open-source font and use those glyphs (like we do for font-awesome?)

**Comment by zepumph** [comment]
@jonathanolson have we used an open source font before? Would that still be translatable?

**Comment by jonathanolson** [comment]
> have we used an open source font before?

Yes, this was required for high-performance label display in webgl for molecule-shapes. See https://github.com/phetsims/sherpa/blob/master/lib/liberation-sans-regular-subset-numeric-degrees.js (has the font data).

> Would that still be translatable?

Only technically yes (my last experiment added ~2MB to the sim to include most characters needed, don't want to reopen that can of worms yet). So basically no.

**Comment by jessegreenberg** [comment]
We observed this in Firefox while working on keyboard nav as well, Firefox crashed on my machine when R is large, see #90.

**Comment by zepumph** [comment]
I found an open source font where I could use the SVG glyph data. I created a new Type called `LiberationSansNode` that works exactly as FontAwesomeNode does, and I used it to draw the R instead. The font is totally off, but it is a proof of concept (the scaling is off as well), the bug is fixed in this dev version:

http://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.3.0-dev.3/resistance-in-a-wire_en.html


I'm not sure where to go from here. I think it may need a design call, I want to do a bit more research before deciding on this approach. As @jonathanolson said before, this will not be translatable. 

I found the font here, and will take a look at other fonts too.

**Comment by zepumph** [comment]
@jessegreenberg @phet-steele can you confirm that this bug is fixed for you guys, I have yet to get my browser to crash, so I can only do so much from over here.

**Comment by jbphet** [comment]
I just checked babel, and there **is** one translation that sets the value of R to something other than R.  However, the translation appears to have added a full word, and it doesn't work well at all, so it seems like the translator missed the point (the translation is Tibetan for anyone who wants to have a look).

Still, I'm not fully comfortable with the idea of making R non-translatable.  Can we simply limit the size of the character, and just add a big red rectangle when a certain point is reached?  Does using accurate bounds for the character make any difference?

**Comment by jessegreenberg** [comment]
Unfortunately, the version in http://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.3.0-dev.3/resistance-in-a-wire_en.html is still crashing for me.

**Comment by jessegreenberg** [comment]
>  Can we simply limit the size of the character, and just add a big red rectangle when a certain point is reached?

This would be my preference too.

**Comment by zepumph** [comment]
>Can we simply limit the size of the character, and just add a big red rectangle when a certain point is reached?

I like that too, I'll see what I can do, and then will pass it off to @ariel-phet to see what he thinks.

**Comment by zepumph** [comment]
> Does using accurate bounds for the character make any difference? 

Could you explain what you mean a bit more.

**Comment by jbphet** [comment]
Scenary Text nodes have an option called 'boundsMethod' that describes how the bounds of a given text node should be calculated.  There is a performance tradeoff with using accurate bounds because it takes longer to calculate, but inaccurate bounds can lead to other problems, like artifacts on the screen, and rendering that is essentially out of the bounds.  My thought was that this might be contributing to the problem.  I thought it would be worthwhile to try 'accurate' for the bounds method and see if it changes the behavior at all (and doesn't introduce any performance issues).

**Comment by jbphet** [comment]
For more info, please check out http://phetsims.github.io/scenery/doc/ and search for 'boundsMethod'.

**Comment by jonathanolson** [comment]
> I thought it would be worthwhile to try 'accurate' for the bounds method

The default boundsMethod is 'accurate'. Is that being overridden here?

**Comment by zepumph** [comment]
I don't believe so, see the instance creations here from FormulaNode:
```js
      var text = new Text( entry.label, {
        font: new PhetFont( { family: ResistanceInAWireConstants.FONT_FAMILY, size: 115 } ),
        fill: entry.color,
        center: entry.position,
        tandem: entry.tandem
      } );

```

**Comment by jessegreenberg** [comment]
I just tried ```fast``` and ```fastCanvas``` ```boundsMethod``` values, still seeing Firefox get stuck.

**Comment by zepumph** [comment]
@jbphet and I were talking about this problem, I think it would be good to add "anti artifact rectangles" behind the text nodes to see if that helps, as done in Ohms-law. Thanks @jbphet for the great name.

```js
      // Add an invisible rectangle with bounds slightly larger than the text so that artifacts aren't left on the
      // screen, see https://github.com/phetsims/ohms-law/issues/26.
      var antiArtifactRectangle = Rectangle.bounds( textNode.bounds.dilatedX( 1 ) );
```

**Comment by zepumph** [comment]
I too @jbphet's advice. I added the 'antiArtifactRectangle' and calculated the text bounds with 'accurate'. Unfortunately this was still not enough to fix the problem.

Then I implemented the workaround where a box shows once the R is 'capped' because it is too big. I am also scaling the lineWidth based on the value of current.

Here is a version of this change, it is really rough. 

http://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.3.0-dev.4/resistance-in-a-wire_en.html

Current problems that I am seeing with it:

1. The lineWidth scaling is pretty sloppy, and if we go down that road it will need to be honed.
2. The R currently doesn't stay in the layout bounds (run with ?dev), which is a bummer, because I don't want to cap it at too much of a smaller size, maybe that is what we will have to do. If we get clever we could probably scale the control panel down a bit and move the left side to the right. 

@ariel-phet would you take a look and see how you like it? I want to know if we are going down the right road. I was unable to get firefox to crash with this dev version, @jessegreenberg please tell me if you have different luck.

**Comment by ariel-phet** [comment]
@zepumph I think you are going to need to find a solution where the "R" can continue to grow. I thought what @jbphet was suggesting was basically at some point, replace the "R" with a rectangle. 

The current behavior is odd and I am guessing Kathy would veto it anyhow. I think we need to hit on a solution that visually acts like the published version.

**Comment by jessegreenberg** [comment]
@zepumph I gave 1.3.0-dev.4 a test.  It sounds like we might not be able to use that solution, but there was no crashing in Firefox with that version.

**Comment by zepumph** [comment]
@ariel-phet you are so right, sorry that I completely missunderstood. I tried to implement it again but by detecting the screen's layoutbounds, and when the 'R' was larger than it, just making the R into a big box, and it still ran into problems. I just realized (at the end of the day) that I was still drawing a potentially HUGE rectangle because it was based on the bounds of the letter. Tomorrow I will look at just making a rectangle the size of the screen bounds, firefox may have an easier time drawing that.

**Comment by zepumph** [comment]
Here is what I have tried so far. Each time firefox has still had a 'flickering' red screen when the R was too big.

* There is an antiartifact around the text. When the letter is bigger than the screen, make that box filled red and set the text to invisible.
* the same as above but remove the text child when it gets too big, and just show the rectangle.

I think that a problem with the above methods is that they are still calculating that box (and possibly text) bounds to be huge, when resistance is 
* have a separate rectangle that is the size of the screen bounds, because potentially that is all that would have to be covered (doesn't look good on other screen sizes like in an IFrame)

So from here I think that I will just try to adjust the scale accordingly to make it look nice both for large and small values. The problem is that the scale needs to account for accuracy up to .01 Ohm, but also up to 2000 Ohms. Some options that I'm thinking about.

* In RIAW there is just a "scale m" if you think about the linear formula `y=mx+b`, but in ohms-law there is also a `b`. I should try adding that to give a bit more control to the scale

* I could also change what the scale of the R is after a certain large point, so it never goes off the screen. This is less accurate, than we probably want to go, so I will table it.

**Comment by zepumph** [comment]
This is the next version. 

http://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.3.0-dev.5/resistance-in-a-wire_en.html

Here I simplified the code up a lot, and rather than detecting an edge case where the R was getting too big, I just scaled the R down so that it looks good through its whole range. Now it is a bit less responsive to small changes. It is hard to notice changes on the order of .01.

It doesn't flicker anymore, sometimes on firefox the R shifts scaling in a weird way, but I'm not entirely sure how to address it. 

@ariel-phet would you look at this one? I have spent a fair amount of time on this issue, and I have struggled more than I thought I would. I want to bring up the time spent on this so that @ariel-phet is aware, and we can discuss further allocation if the current solution isn't good, or needs refining. 

@jessegreenberg does this crash for you on firefox, as I can't get it to.

**Comment by jessegreenberg** [comment]
No breaking in Firefox for me @zepumph.  It will still pause sometimes, when dragging quickly it will get to about 1.46 cm^2 and stall for about 11 seconds before snapping to 0.01cm^2. But a Firefox is able to recover with the smaller R.

**Comment by jessegreenberg** [comment]
When dragging slowly, I can get much farther before it seizes, it gets to 0.08 cm^2 consistently and then pauses before snapping to 0.01 cm^2.

**Comment by jessegreenberg** [comment]
I replaced

```js
      var text = new Text( entry.label, {
        font: new PhetFont( { family: ResistanceInAWireConstants.FONT_FAMILY, size: 115 } ),
        fill: entry.color,
        center: entry.center,
        tandem: entry.tandem,
        boundsMethod: 'accurate'
      } );
```

With 
```js
      var text = new Rectangle( 0, 0, 50, 50, {
        center: entry.center,
        fill: entry.color
      } );
```

And Firefox pauses for ~3 seconds when the values changes from ~1.2 cm^2 to 0.01 cm^2.

**Comment by zepumph** [comment]
@jessegreenberg and I just screen shared to discuss this, and we found that this time there were no issues with dev.5

Neither my issues stated above, or @jessegreenberg's were present. This makes me feel better about this issue being closer to solved. Since it is inconsistently a minor problem (never crashing the browser, and only sometimes lagging it down at large values), I think of this an improvement from the beginning of this issue.

@ariel-phet I don't want you to have to look back at this whole string of messages. I would love two pieces of feedback from you:
1. Run in firefox, do you experience any buggy laggy behavior? If so is it bad enough that you would like us to continue on and fix it?
2. (any browser) Does the scaling of the 'R' vary enough when resistance is low (less than .1 ohms)? 

Thanks!

**Comment by ariel-phet** [comment]
@zepumph - I am definitely getting buggy/laggy behavior on FF

perhaps bring up at dev meeting to brainstorm the issue and possible solutions?

I am OK with the time you are spending. Obviously it is over something very "nit picky" but I figure (despite some frustration you might be having) you are getting to learn a thing or two :).

**Comment by zepumph** [comment]
I am indeed learning! I don't mind taking the time it takes at all, I just wanted to check in to make sure we are all on the same page. I'll mark it for dev meeing next week (since I will be gone for the meeting this week) to see if there are any thoughts on the matter.

**Comment by zepumph** [comment]
Actually I decided to poke around a bit more this morning and I think I fixed the laggy behavior. I decreased the font size, which I think was a lot of the computation in Firefox. Then I increased the scale so that the letters are pretty much the same size. @ariel-phet could you see if this version looks better. 
http://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.3.0-dev.6/resistance-in-a-wire_en.html

If we think that it is fixed, then we can pixel polish from there, let me know what needs to be done.

**Comment by ariel-phet** [comment]
@zepumph looking good to me in latest version!

**Comment by ariel-phet** [comment]
Well - the "R" behavior anyhow. There is some bouncing around of sim elements, but I believe that is a known issue for you

**Comment by zepumph** [comment]
@ariel-phet that is great news!! The 'jostling' or bouncing is in both OL and RIAW, and is being addressed in https://github.com/phetsims/ohms-law/issues/68.

As for this issue. I defer to you as the designer to report if there is any pixel polishings/minor scaling changes that you would like to do with the R before closing. I set a scale that looked "pretty good" to me, but I didn't try to make it spot on, since I was just prototyping solutions.

Let me know if there is more to be done.

**Comment by zepumph** [comment]
If changes are small, it could be nice to complete them today before I create a dev release for accessibility work. My plan was to get RIAW into dev testing before I leave tomorrow.

**Comment by ariel-phet** [comment]
@zepumph a few polishes:

1. the "rho" should be properly aligned with the "L" (see the published version). The vertical alignment of "rho" and "L" is correct in the control panel but not in the equation

![raiw1](https://user-images.githubusercontent.com/4051174/28840890-a94ad99a-76b5-11e7-991c-e2d7997a12b1.PNG)
![riaw-dev](https://user-images.githubusercontent.com/4051174/28840889-a94296ae-76b5-11e7-9e5e-576924f38960.PNG)

2. The "R" scaling probably needs some tweaking - will slack you

**Comment by zepumph** [comment]
Thanks @ariel-phet, let's pick up these pixel polishes in a new issue. Closing

**Comment by phet-steele** [comment]
Can confirm I'm not crashing anymore 👍 👍 👍 .

**Comment by phet-steele** [comment]
For the record, @EthanWJohnson DOES see flickering on Win 10 FF 53.0.2, but does NOT see flickering after updating FF to 54.0.1.
