### ISSUE TITLE
Double string test problem with the Ohm symbol

### ISSUE THREAD

**Issue by zepumph** [phetsims/resistance-in-a-wire#81]
It looks like there are some problems in how the Ohm cm unit is being i18lized.

![image](https://cloud.githubusercontent.com/assets/6856943/25445566/ef62ce7e-2a6b-11e7-8814-cbdbe9261239.png)

**Comment by phet-steele** [comment]
@samreid @zepumph, there isn't a problem because this string is a double pattern:

this: {0}{1}

becomes {0}:{0}{1}:{1}:{0}:{0}{1}:{1}

There as been discussion here: phetsims/chipper/issues/413, and keep in mind that `?stringTest=double` is only used for testing but is, in this case, not revealing a true problem for any translator.

**Comment by samreid** [comment]
Thanks @phet-steele.  @zepumph can you please see if that all makes sense?

**Comment by zepumph** [comment]
Thanks @phet-steele, that is great. Closing
